### PR TITLE
[MSF 8] WIP Add class methods

### PR DESCRIPTION
**Pull request by dustineichler**
If applied, adds support for `.first` and `.filter(q:"foo")` where `NetworkInterface` would either return the first ipv4 address or instead filter for any available address.

Resolves https://github.com/rapid7/network_interface/issues/8

### CODE REVIEW

**Comment by dustineichler** [comment]
I'm not sure how valuable this is. I have test coverage I need to fix, but will push up shortly. I've also been looking at the C code here and elsewhere.

**Comment by wvu-r7** [comment]
Is this still WIP?

**Comment by dustineichler** [comment]
@wvu-r7 yes. i'll have time later in the week to circle back on this.

**Comment by busterb** [comment]
Howdy, any time to finish this up? I've got some code to fix the specs that builds on this, will push up to this branch.

**Comment by dustineichler** [comment]
@busterb yes. i'll look at this asap. this weekend if i can.

**Comment by wvu-r7** [comment]
Thanks, @dustineichler!

**Comment by dustineichler** [comment]
@busterb few more minor changes to make and cleanup, but this is further along.

**Comment by wvu-r7** [comment]
Will reopen when we have time.

**Pull request closed without merging**
